config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :orders, only: [:index, :show, :payment, :order, :success, :destroy, :confirmation, :update]
  resources :types, only: [:index, :show]
  resources :collections, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :products, only: [:index, :show]
  resources :pages, only: [:show]
  resources :order_items
  resource :cart, only: [:show]
  root "static#homepage"
  #get "/cart" => 'static#cart', as: "cart"
  get "/order" => "orders#order"
  get "/confirmation" => "orders#confirmation"
  get "/success" => "orders#success"
  put :delete_picture, controller: :products
  post :create_order, controller: :orders
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :type, optional: true
  has_many :products
end

app/models/collection.rb
class Collection < ApplicationRecord
	has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  before_save :update_total
  before_create :update_status

  def calculate_total
    self.order_items.collect { |item| item.product.computed_price * item.quantity }.sum
  end

  private

  def update_status
    if self.status == nil?
      self.status = "Создан"
    end
  end

  def update_total
    self.total = calculate_total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :product
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :product, optional: true
  has_attached_file :attachment, styles: { medium: "400x400#", thumb: "40x60>", original: "600x900>" }, :convert_options => { :thumb => '-quality 100' }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :attachment, content_type: /\Aimage\/.*\z/
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :type, optional: true
  belongs_to :category, optional: true
  belongs_to :collection, optional: true
  has_many :pictures, :dependent => :destroy, :validate => false
  accepts_nested_attributes_for :pictures, allow_destroy: true

  before_save :update_properties
  after_save :update_attachments

  self.per_page = 12

  def pictures_from_urls(urls)
    urls.each do |url|
      self.pictures.create(attachment: open(url))
    end
  end

  def computed_price
    price = (self.price.split("-")[1] || self.price.split("-")[0]).to_i
    percentage_price = price + ((price/100)*33) #33%UP
    percentage_price.round(-2)-1 #99 ROUND
  end

  private
    def update_properties
      updater = Adapter::Store.new(self)
      updater.get_fields
    end

    def update_attachments
      if !self.pictures.first
        self.pictures_from_urls(self.additional)
      end
    end
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :categories
  has_many :products
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @order_items = current_order.order_items
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :create, :update, :destroy]


  def show
  end

  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /Pages/1
  # PATCH/PUT /Pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /Pages/1
  # DELETE /Pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_page
      @page = Page.find(params[:id])
    end

    def page_params
      params.require(:page).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    = display_meta_tags site: 'Novalook.ru'
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application'
  %body
    .container
      = render 'shared/header'
      = render 'shared/navbar'
      = yield
      = render 'shared/footer'
      = render 'shared/metrika'
:javascript
  feather.replace()

app/views/pages/show.html.haml
.text-center
  %h1
    = @page.name
  %p
    = @page.description.html_safe

app/views/shared/_footer.html.haml
.footer
  .p
    © 2019 NOVALOOK.RU
  %ul.list-inline
    - Page.all.each do |page|
      %li.list-inline-item
        = link_to page.name, page
  .payments-splash
    = image_tag 'payments.svg', class: 'img-fluid'

app/views/shared/_header.html.haml
.header
  .row
    .col-lg-12.d-md-none
      .logo
        = link_to image_tag('logo.svg'), root_path
    .col-lg-12.d-sm-none
      .user-links.center.fixed-bottom.bottom-links
        %ul.list-inline
          %li.list-inline-item
            = link_to "https://instagram.com/novalook.ru" do
              %i{:data=> {:feather => "instagram"}}
          %li.list-inline-item
            %a{:href => "#"}
              %i{:data=> {:feather => "user"}}
          %li.list-inline-item
            = link_to cart_path do
              %i{:data=> {:feather => "shopping-bag"}}
              .badge.badge-success.counter
                = current_order.order_items.count
    .col-lg-3.col-md-4.col-6.d-none.d-sm-block
      .user-links.left
        %ul.list-inline
          %li.list-inline-item
            = link_to "https://instagram.com/novalook.ru" do
              %i{:data=> {:feather => "instagram"}}
    .col-lg-6.col-md-4.d-none.d-md-block
      .logo
        = link_to image_tag('logo.svg'), root_path
    .col-lg-3.col-md-4.col-6.d-none.d-sm-block
      .user-links.right
        %ul.list-inline
          %li.list-inline-item
            %a{:href => "#"}
              %i{:data=> {:feather => "user"}}
          %li.list-inline-item
            = link_to cart_path do
              %i{:data=> {:feather => "shopping-bag"}}
              .badge.badge-success.counter
                = current_order.order_items.count

app/views/shared/_metrika.html.haml
/ Yandex.Metrika counter
:javascript
  (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
  m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
  (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

  ym(52247083, "init", {
       id:52247083,
       clickmap:true,
       trackLinks:true,
       accurateTrackBounce:true,
       webvisor:true
  });
%noscript
  %div
    %img{:alt => "", :src => "https://mc.yandex.ru/watch/52247083", :style => "position:absolute; left:-9999px;"}/
/ /Yandex.Metrika counter

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light

  %button.navbar-toggler{"aria-controls" => "navbarNavDropdown", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNavDropdown", "data-toggle" => "collapse", :type => "button"}
    %i{:data=> {:feather => "menu"}} 
    %div.catalog-nav-link
      Каталог
  #navbarNavDropdown.collapse.navbar-collapse
    %ul.navbar-nav
      - Type.all.each do |type|
        %li.nav-item.dropdown
          = link_to type.name, '',class: 'nav-link', id: type.id, aria: {expanded: false, haspopup: true}, data: {toggle: 'dropdown'}, role: 'button'
          .dropdown-menu{aria:{labelledby: type.id}}
            - type.categories.each do |category|
              = link_to category.name, category, class: 'dropdown-item'
      - if Collection.all
        %li.nav-item.dropdown
          = link_to 'Коллекции', '', class: 'nav-link', aria: {expanded: false, haspopup: true}, data: {toggle: 'dropdown'}, role: 'button'
          .dropdown-menu
            - Collection.all.each do |collection|
              = link_to collection.name, collection, class: 'dropdown-item'

app/views/shared/_product_breadcrumbs.haml
%ul.breadcrumbs.list-inline
  %li.list-inline-item
    = link_to "Главная", root_path
    &nbsp;&rarr;
  %li.list-inline-item
    = ((link_to @product.category.type.name, type_path(@product.category.type_id)) rescue 'Тип')
    &nbsp;&rarr;
  %li.list-inline-item
    = ((link_to @product.category.name, category_path(@product.category_id)) rescue 'Категория')
    &nbsp;&rarr;
  %li.list-inline-item
    = @product.name

app/views/shared/_product_form.haml
= form_for @order_item, html: {class: 'order-form'} do |f|
  = f.hidden_field :product_id, value: @product.id
  %p
    Размер:
    = f.select :size, @product.size.map {|i| i['value']}, {},class: 'form-control'
    %a{:class => "small size-table", :href => ""} Таблица размеров
  %p
    Цвет:
    = f.select :color, @product.color.map {|i| i['color']}, {},class: 'form-control'
  %p
    Количество:
    = f.select :quantity, ((1..5).map {|i| [i,i] }), {}, class: 'form-control'
  %p.price
    %strong 
      = @product.computed_price.to_s + ' ₽'
    %span.free-delivery
      + бесплатная доставка
  .cta
    %span.add
      = f.submit "Добавить в корзину", class: 'btn btn-lg btn-outline-danger'